export const SCROLL_CONFIG = {
  ROW_HEIGHT: 32,
  VIEWPORT_HEIGHT: 400,
  BUFFER_ROWS: 10,
}

export const TRANSACTION_CONFIG = {
  INITIAL_BATCH: 10_000,
  UPDATE_INTERVAL_MS: 200,
  MAX_TRANSACTIONS: 15000,
}